services:
  laboratorio-api:
    build: .
    container_name: laboratorio-api
    env_file:
      - .env
    ports:
      - "${PORT:-8000}:${PORT:-8000}"
    environment:
      PORT: ${PORT:-8000}
    restart: unless-stopped
