from __future__ import annotations

import os
from contextlib import contextmanager
from typing import Any, Iterator, Protocol

try:
    from dotenv import load_dotenv
except ImportError:  # pragma: no cover - optional in simple local installs
    load_dotenv = None


if load_dotenv:
    load_dotenv()


DATABASE_URL = os.getenv("DATABASE_URL")


class CursorLike(Protocol):
    def fetchone(self) -> Any: ...

    def fetchall(self) -> list[Any]: ...


class ConnectionLike(Protocol):
    def execute(
        self,
        query: str,
        params: tuple[Any, ...] | list[Any] = (),
    ) -> CursorLike: ...

    def commit(self) -> None: ...

    def rollback(self) -> None: ...

    def close(self) -> None: ...


class DatabaseConnection:
    def __init__(self, connection: Any) -> None:
        self._connection = connection

    def execute(self, query: str, params: tuple[Any, ...] | list[Any] = ()) -> CursorLike:
        query = _to_postgres_placeholders(query)
        return self._connection.execute(query, params)

    def commit(self) -> None:
        self._connection.commit()

    def rollback(self) -> None:
        self._connection.rollback()

    def close(self) -> None:
        self._connection.close()


def _to_postgres_placeholders(query: str) -> str:
    return query.replace("?", "%s")


def _connect_postgres() -> DatabaseConnection:
    if not DATABASE_URL:
        raise RuntimeError(
            "DATABASE_URL es obligatorio. Configura la cadena de conexion PostgreSQL."
        )

    try:
        import psycopg
        from psycopg.rows import dict_row
    except ImportError as error:
        raise RuntimeError(
            "Falta instalar psycopg. Ejecuta: pip install -r requirements.txt"
        ) from error

    connection = psycopg.connect(DATABASE_URL, row_factory=dict_row)
    return DatabaseConnection(connection)


def _connect() -> ConnectionLike:
    return _connect_postgres()


@contextmanager
def get_db() -> Iterator[ConnectionLike]:
    connection = _connect()
    try:
        yield connection
        connection.commit()
    except Exception:
        connection.rollback()
        raise
    finally:
        connection.close()


def execute_insert(
    connection: ConnectionLike,
    query: str,
    params: tuple[Any, ...] | list[Any] = (),
) -> int:
    cursor = connection.execute(f"{query.rstrip()} RETURNING id", params)
    row = cursor.fetchone()
    return int(row["id"])


def _init_postgres(connection: ConnectionLike) -> None:
    statements = [
        """
        CREATE TABLE IF NOT EXISTS sustancias (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            nombre TEXT NOT NULL,
            categoria TEXT NOT NULL,
            cantidad DOUBLE PRECISION NOT NULL DEFAULT 0 CHECK (cantidad >= 0),
            unidad TEXT NOT NULL,
            nivel_riesgo TEXT NOT NULL,
            ubicacion TEXT NOT NULL,
            responsable TEXT NOT NULL,
            cantidad_minima DOUBLE PRECISION NOT NULL DEFAULT 0 CHECK (cantidad_minima >= 0),
            cantidad_maxima DOUBLE PRECISION CHECK (
                cantidad_maxima IS NULL OR cantidad_maxima >= 0
            ),
            created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS movimientos (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            id_sustancia INTEGER NOT NULL REFERENCES sustancias (id),
            tipo TEXT NOT NULL CHECK (tipo IN ('entrada', 'salida')),
            cantidad DOUBLE PRECISION NOT NULL CHECK (cantidad > 0),
            motivo TEXT NOT NULL,
            fecha TIMESTAMPTZ NOT NULL DEFAULT NOW()
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS usuarios (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            nombre TEXT NOT NULL,
            contrasena TEXT NOT NULL,
            rol TEXT NOT NULL CHECK (
                rol IN ('administrador', 'responsable', 'consultor')
            ),
            created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
        )
        """,
        "CREATE INDEX IF NOT EXISTS idx_sustancias_nombre ON sustancias (nombre)",
        "CREATE INDEX IF NOT EXISTS idx_sustancias_categoria ON sustancias (categoria)",
        "CREATE INDEX IF NOT EXISTS idx_sustancias_nivel_riesgo ON sustancias (nivel_riesgo)",
        "CREATE INDEX IF NOT EXISTS idx_movimientos_id_sustancia ON movimientos (id_sustancia)",
    ]

    for statement in statements:
        connection.execute(statement)


def init_db() -> None:
    with get_db() as connection:
        _init_postgres(connection)
